baseURL = "https://bestsamina.github.io/"
languageCode = "en-us"
theme = "personal-web"
title = "Samina Website"
copyright = "@Samina Fu"
googleAnalytics = "ca-pub-6396786781922729"
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hi, I'm Samina 👋"
  sub = "This is my Life & Technological Journey"

[taxonomies]
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#D250F4"
  mainSections = ['posts']

[params.notFound]
  gopher = "/images/gopher.png"
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = ''
  gradientOverlay = ''
  logo = "/images/person.jpg"

[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  github = "https://github.com/sufuf3"
  twitter = "https://twitter.com/sufuf3149"
  medium = "https://medium.com/@sufuf3149"
  gitlab = "https://gitlab.com/sufuf3"

[params.contact]
  email = ""
  text= ""


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = 2

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  title = "Tags"
  url = "/tags/"
  weight = 3

[[menu.main]]
  identifier = "Categories"
  name = "Categories"
  title = "Categories"
  url = "/categories/"
  weight = 4

[[menu.main]]
  identifier = "awesome-blogs"
  name = "Awesome-blogs"
  title = "Awesome-blogs"
  url = "/page/awesome-blogs/"
  weight = 5

[[menu.main]]
  identifier = "blog"
  name = "Post"
  title = "Blog section"
  url = "/posts/"
  weight = 1

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false

[params.meta]
    description = "Life & Technological Journey of Samina - Hello and welcome to my blog. My name is Samina Fu. This blog is about technology and the record of my life. Hope the logs can help you and me someday."
    keywords = "blog,python,golang,javascript,container,opencord,cord,sdn,network"

[params.main]
  latestPublishHeader = ""