baseURL = "https://bestsamina.github.io/"
languageCode = "en-us"
theme = "hyde-hyde"
title = "Life & Technological Journey of Samina"
copyright = "Samina Fu"

## Hugo Built-in Features
disqusShortname = "bestsamina"
enableEmoji = true


[permalinks]
    post = "/:year/:month/:day/:slug/"
    series = "/:year/:month/:day/:slug/"

#[Taxonomies]
#    tag = "tags"
#    series = "series"
#    series-desc = "series-desc"

[params]
    author = "Samina Fu"
    description = "This blog is about technology and the record of my life. Hope the logs can help you and me someday."
    authorimage = "images/sufuf3_1519028337_878.jpg"
    dateFmt = "Jan 02, 2006"
    dateformat = "Jan 2, 2017"
    highlightjs = true
    mainSections = ["posts"]

## Site Meta Settings
[params.meta]
    description = "Life & Technological Journey of Samina - Hello and welcome to my blog. My name is Samina Fu. This blog is about technology and the record of my life. Hope the logs can help you and me someday."
    keywords = "blog,python,golang,javascript,container,opencord,cord,sdn,network"


## Social Accounts
[params.social]
    twitter = "sufuf3149"
    github = "sufuf3"
    gitlab = "sufuf3"

## Main Menu
[[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/posts/"
    weight = 1

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"

[[menu.main]]
    url = "/series/"
    identifier = "series"
    name = "Series"
    weight = 2

[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 3

[[menu.main]]
    url = "/categories/"
    name = "Categories"
    weight = 4

[[menu.main]]
    url = "/page/awesome-blogs"
    name = "awesome-blogs"
    weight = 5

# https://gohugo.io/content-management/related
[related]
    # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
    threshold = 80
    # To get stable "See also" sections we, by default, exclude newer related pages.
    includeNewer = false
    # Will lower case keywords in both queries and in the indexes.
    toLower = false

[[related.indices]]
    name  = "tags"
    weight = 100
[[related.indices]]
    name = "keywords"
    weight = 150
